/*
 * File: app/controller/GonogoView.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.GonogoView', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            mainnav: 'mainnav',
            gonogoview: 'gonogoview',
            gonogoitem: 'gonogoitem',
            gonogochecklistview: 'gonogochecklistview',
            navigationbar: 'mainnav #navigationbar',
            gonogoservices: 'gonogoservices',
            checklistview: 'checklistview',
            checklist: 'checklist'
        },

        control: {
            "gonogoview": {
                show: 'onTabpanelShow',
                activeitemchange: 'onTabpanelActiveItemChange'
            },
            "gonogoservices #viewchecklist": {
                tap: 'onViewTapButton'
            },
            "gonogoitem #gonogobutton": {
                tap: 'onButtonTap'
            },
            "gonogoservices #editchecklist": {
                tap: 'onEditTapButton'
            }
        }
    },

    onTabpanelShow: function(component, eOpts) {
        //Récupération du store
        var sto = Ext.getStore('itemsgonogo');

        sto.filter('finished', 'false');
    },

    onTabpanelActiveItemChange: function(container, value, oldValue, eOpts) {
        //Récupération du store
        var sto = Ext.getStore('itemsgonogo');

        //On efface tous les filtres existants
        sto.clearFilter();

        if (value.config.title !== 'History') {
            sto.filter('finished', 'false');
        }
    },

    onViewTapButton: function(button, e, eOpts) {
        var mainNavView = this.getMainnav();
        var navBarMainView = this.getNavigationbar();

        var gonogoCheckListView = this.getGonogochecklistview();

        var serviceNameId = button.up('gonogoservices').getRecord().get('id');
        var serviceName = button.up('gonogoservices').getRecord().get('label');

        var gonogoName = mainNavView.down('gonogochecklistview').down('#navigationbar').getTitle().getTitle();

        //Récupération du store
        var sto = Ext.getStore('checklistservices');
        //On efface tous les filtres existants
        sto.clearFilter();

        var previousTitleMainView = navBarMainView.getTitle();

        sto.filter('service', serviceNameId);

        mainNavView.push({
            title : previousTitleMainView,
            xtype : 'checklistlist'
        });

        mainNavView.down('checklistlist').down('#navigationbar').setTitle(gonogoName+' - '+serviceName);
        localStorage.setItem("gonogoMode", "view");

        mainNavView.down('checklistlist').down('#savechecklist').hide();
    },

    onButtonTap: function(button, e, eOpts) {
        var gonogoItemName = button.up('gonogoitem').getRecord().get('label');

        var mainNavView = this.getMainnav();
        var navBarMainView = this.getNavigationbar();

        var previousTitleMainView = navBarMainView.getTitle();

        mainNavView.push({
            title : previousTitleMainView,
            xtype : 'gonogochecklistview'
        });

        mainNavView.down('gonogochecklistview').down('#navigationbar').setTitle(gonogoItemName);

        localStorage.setItem("gonogoName", gonogoItemName);
    },

    onEditTapButton: function(button, e, eOpts) {
        var mainNavView = this.getMainnav();
        var navBarMainView = this.getNavigationbar();

        var gonogoCheckListView = this.getGonogochecklistview();

        var serviceNameId = button.up('gonogoservices').getRecord().get('id');
        var serviceName = button.up('gonogoservices').getRecord().get('label');

        var gonogoName = mainNavView.down('gonogochecklistview').down('#navigationbar').getTitle().getTitle();

        //Récupération du store
        var sto = Ext.getStore('checklistservices');
        //On efface tous les filtres existants
        sto.clearFilter();

        var previousTitleMainView = navBarMainView.getTitle();

        if (serviceName == localStorage.getItem('userservice')){
            sto.filter('service', serviceNameId);

            mainNavView.push({
                title : previousTitleMainView,
                xtype : 'checklistlist'
            });

            mainNavView.down('checklistlist').down('#navigationbar').setTitle(gonogoName+' - '+serviceName);
            localStorage.setItem("gonogoMode", "edit");

            mainNavView.down('checklistlist').down('#savechecklist').show();
        }
        else {
            alert('You don\'t have the permissions for doing that...');
        }
    }

});