/*
 * File: app/controller/AuthView.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.AuthView', {
    extend: 'Ext.app.Controller',

    config: {
        views: [
            'AuthView',
            'MainNav'
        ],

        refs: {
            mainnav: '#mainnav',
            authview: '#authview',
            loginButton: '#loginButton',
            loginField: '#loginField',
            passwordField: '#passwordField',
            errorAuthText: '#errorAuthText'
        },

        control: {
            "#loginButton": {
                tap: 'onLoginTapButton'
            }
        }
    },

    onLoginTapButton: function(button, e, eOpts) {
        var loginField = Ext.getCmp('loginField');
        var passwordField = Ext.getCmp('passwordField');
        var label = Ext.getCmp('errorAuthText');

        label.hide();

        var login = loginField.getValue();
        var password = passwordField.getValue();

        if (login != 'admin' || password != 'adminadmin') {
            label.show();     
        }
        else {
            var sample = Ext.create('MyApp.view.MainNav');
            Ext.Viewport.setActiveItem(sample);
        }

        loginField.setValue('');
        passwordField.setValue('');
    }

});