/*
 * File: app/controller/DownloadDocuments.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.DownloadDocuments', {
    extend: 'Ext.app.Controller',
    alias: 'controller.downloaddocuments',

    config: {
        refs: {
            downloaddocumentslist: 'downloaddocumentslist'
        },

        control: {
            "downloaddocumentslist": {
                itemtap: 'onListItemTap'
            }
        }
    },

    onListItemTap: function(dataview, index, target, record, e, eOpts) {
        Ext.Msg.confirm(
            "Download document",
                "Would you like to download "+record.get('name_doc'),
                    function(buttonId) {
                        if (buttonId === 'yes') {
                            //TODO retrieve the file .. new panel ?
                            window.open(document.URL+record.get('name_doc'));
                            //alert(document.URL);
                        }
                    }
                );


    }

});