/*
 * File: app/controller/FopNavView.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.FopNavView', {
    extend: 'Ext.app.Controller',
    alias: 'controller.fopnavview',

    config: {
        refs: {
            mainnav: 'mainnav'
        },

        control: {
            "#fopmaingrid": {
                itemtap: 'onGridItemTap'
            },
            "#fopdetailgrid": {
                itemdoubletap: 'onGridItemDoubletap'
            }
        }
    },

    onGridItemTap: function(dataview, index, target, record, e, eOpts) {
        var mainNavView = this.getMainnav();
        //alert(record.get('C'));
        mainNavView.pop();
        mainNavView.push({
            title : "Detail",
            xtype : 'fopdetailview'
        });
    },

    onGridItemDoubletap: function(dataview, index, target, record, e, eOpts) {
        alert(record.get('Status'));
    },

    launch: function() {
        var fopStore = Ext.getStore('ItemFopDetail');
        timerFop = setInterval(function checkForNotifications() {
            fopStore.load();
        },5000);
    }

});