/*
 * File: app/controller/GonogoView.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.GonogoView', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            mainnav: 'mainnav',
            gonogoview: 'gonogoview',
            gonogoitem: 'gonogoitem',
            gonogochecklistview: 'gonogochecklistview',
            navigationbar: 'mainnav #navigationbar'
        },

        control: {
            "gonogoview": {
                show: 'onTabpanelShow',
                activeitemchange: 'onTabpanelActiveItemChange'
            },
            "gonogoitem #gonogobutton": {
                tap: 'onButtonTap'
            }
        }
    },

    onTabpanelShow: function(component, eOpts) {
        //Récupération du store
        var sto = Ext.getStore('itemsgonogo');

        sto.filter('finished', 'false');
    },

    onTabpanelActiveItemChange: function(container, value, oldValue, eOpts) {
        //Récupération du store
        var sto = Ext.getStore('itemsgonogo');

        //On efface tous les filtres existants
        sto.clearFilter();

        if (value.config.title !== 'History') {
            sto.filter('finished', 'false');
        }
    },

    onButtonTap: function(button, e, eOpts) {
        var gonogoItemName = button.up('gonogoitem').getRecord().get('label');

        var mainNavView = this.getMainnav();
        var navBarMainView = this.getNavigationbar();

        var previousTitleMainView = navBarMainView.getTitle();

        //var GonogoCheckListView = Ext.create('MyApp.view.GonogoCheckListView');

        mainNavView.push({
            title : previousTitleMainView,
            xtype : 'gonogochecklistview'
        });

        mainNavView.down('gonogochecklistview').down('#navigationbar').setTitle(gonogoItemName);
    }

});