/*
 * File: app/controller/MainNav.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.MainNav', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            menulist: 'menulist',
            mainnav: 'mainnav',
            authview: 'authview',
            menubutton: '#menubutton',
            notificationsbutton: '#notificationsbutton',
            notificationslist: '#notificationslist'
        },

        control: {
            "#menulist": {
                itemtap: 'onListItemTap'
            },
            "#preferencesbutton": {
                tap: 'onPreferencesButtonTap'
            },
            "#logoutbutton": {
                tap: 'onLogOutButtonTap'
            },
            "#notificationsbutton": {
                tap: 'onNotificationsButtonTap'
            }
        }
    },

    onListItemTap: function(dataview, index, target, record, e, eOpts) {
        //On masque d'abord le menu
        var menuListOverlay = Ext.Viewport.getComponent('menulist');
        menuListOverlay.hide();

        var mainNavView = this.getMainnav();

        mainNavView.push({
            title : record.get('label'),
            xtype : record.get('id_view')
        });
    },

    onPreferencesButtonTap: function(button, e, eOpts) {
        //On masque d'abord le menu
        var menuListOverlay = Ext.Viewport.getComponent('menulist');
        menuListOverlay.hide();

        var mainNavView = this.getMainnav();

        mainNavView.push({
            title : 'Preferences',
            xtype : 'preferencesview'
        });
    },

    onLogOutButtonTap: function(button, e, eOpts) {
        //Fonction appelée lors d'un clic sur le bouton "Log out"

        //On masque d'abord le menu
        var menuListOverlay = Ext.Viewport.getComponent('menulist');
        menuListOverlay.hide();

        //Suppression de la variable de session
        localStorage.removeItem("authOK");

        //Arrêt du timer pour la mise à jour des notifications
        clearInterval(timerCheckForNotifications);

        //Redirection vers la page d'authentification
        Ext.Viewport.setActiveItem(0);

        var mainNavView = this.getMainnav();
        Ext.Viewport.remove(mainNavView);
    },

    onNotificationsButtonTap: function(button, e, eOpts) {
        var newNotifNbToHighlight = localStorage.getItem('newNotifNb') - localStorage.getItem('previousNotifNb');

        var itemClass = Ext.get('notificationslist').dom.getElementsByClassName("x-list-item");
        for (var i = 0; i < itemClass.length; i++) {
            if(i < newNotifNbToHighlight){
                itemClass[i].style.backgroundColor='#c7f3c7'; //change the color of the row
            }
            else {
                itemClass[i].style.backgroundColor='#ffffff'; //change the color of the row
            }
        }

        button.setBadgeText('');
        localStorage.setItem("previousNotifNb", localStorage.getItem("newNotifNb"));
    },

    launch: function() {
        var MenuListView = Ext.create('MyApp.view.MenuList');
        var overlayMenuList = Ext.Viewport.add(MenuListView);

        var NotificationsListView = Ext.create('MyApp.view.NotificationsList');
        var overlayNotificationsList = Ext.Viewport.add(NotificationsListView);

        Ext.Viewport.on(
            {
                delegate: '#notificationsbutton',
                tap: function(button) {
                    // When you tap on a button, we want to show the overlay by the button we just tapped.
                    overlayNotificationsList.showBy(button);
                }
            }
        );

        Ext.Viewport.on(
            {
                delegate: '#menubutton',
                tap: function(button) {
                    // When you tap on a button, we want to show the overlay by the button we just tapped.
                    overlayMenuList.showBy(button);
                }
            }
        );

        //On enregistre le nombre de notifications
        var notificationsStore = Ext.getStore('notificationsstore');
        localStorage.setItem("previousNotifNb", 0);

        //Démarrage du timer pour la mise à jour du store des notifications
        timerCheckForNotifications = setInterval(function checkForNotifications() {
            notificationsStore.load();
            localStorage.setItem("newNotifNb", notificationsStore.getAllCount());
            var newNotifNbToPrint = localStorage.getItem('newNotifNb') - localStorage.getItem('previousNotifNb');
            if (newNotifNbToPrint !== 0) {
                Ext.getCmp('notificationsbutton').setBadgeText(newNotifNbToPrint);
                }
        },5000);
    }

});