/*
 * File: app/controller/ProjectSolvingNav.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.ProjectSolvingNav', {
    extend: 'Ext.app.Controller',
    alias: 'controller.projectsolvingnav',

    config: {
        refs: {
            projectsolvingnav: 'projectsolvingnav',
            projectsolvinglist: 'projectsolvinglist'
        },

        control: {
            "projectsolvinglist": {
                itemtap: 'onListItemTap'
            }
        }
    },

    onListItemTap: function(dataview, index, target, record, e, eOpts) {
        var projectSolvingNavView = this.getProjectsolvingnav();

        projectSolvingNavView.pop();

        projectSolvingNavView.push({
            title : record.get('name'),
            xtype : record.get('id_view')
        });
    }

});