/*
 * File: app/controller/QuestionNav.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.QuestionNav', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            questionsnestedlist: 'questionsnestedlist',
            questionsnav: 'questionsnav'
        },

        control: {
            "nestedlist": {
                itemtap: 'onNestedlistItemTap'
            }
        }
    },

    onNestedlistItemTap: function(nestedlist, list, index, target, record, e, eOpts) {
        if (record.get('leaf')===true){
         var questionsNavView = this.getQuestionsnav();
         questionsNavView.pop();
            questionsNavView.push({
                    xtype:'container',
                    scrollable:true,
                    items:[
                    {
                      xtype:'panel',
                      html: '<div style="-webkit-overflow-scrolling:touch; overflow:auto;width=100%;height=100%;position:fixed;top:0;left:0;float:left;z-index:99;""><iframe style=position:fixed;top:0;left:0;float:left;z-index:1;" width="100%" height="100%" src=\"http://37.59.48.149:12080/w/index.php/'+record.get('wiki')+'\"</iframe></div>'
                    }
                        ]});

        }

    }

});