/*
 * File: app/view/FopDetailView.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.FopDetailView', {
    extend: 'Ext.Panel',
    alias: 'widget.fopdetailview',

    requires: [
        'Ext.grid.Grid',
        'Ext.grid.column.Column'
    ],

    config: {
        items: [
            {
                xtype: 'grid',
                docked: 'top',
                height: 1136,
                id: 'fopdetailgrid',
                store: 'ItemFopDetail',
                title: 'FOPDetailGrid',
                columns: [
                    {
                        xtype: 'column',
                        width: 110,
                        dataIndex: 'Line',
                        text: 'Line'
                    },
                    {
                        xtype: 'column',
                        width: 170,
                        dataIndex: 'Action',
                        text: 'Action'
                    },
                    {
                        xtype: 'column',
                        width: 130,
                        dataIndex: 'Entity',
                        text: 'Entity'
                    },
                    {
                        xtype: 'column',
                        width: 130,
                        dataIndex: 'Label',
                        text: 'Label'
                    },
                    {
                        xtype: 'column',
                        width: 130,
                        dataIndex: 'Time',
                        text: 'Time'
                    },
                    {
                        xtype: 'column',
                        width: 160,
                        dataIndex: 'Report',
                        text: 'Report'
                    }
                ]
            }
        ]
    }

});