/*
 * File: app/view/GonogoServices.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.GonogoServices', {
    extend: 'Ext.dataview.component.DataItem',
    alias: 'widget.gonogoservices',

    requires: [
        'Ext.field.Hidden',
        'Ext.field.Checkbox',
        'Ext.Button'
    ],

    config: {
        disabled: false,
        maxHeight: 70,
        padding: 10,
        layout: {
            type: 'hbox',
            align: 'center',
            pack: 'center'
        },
        items: [
            {
                xtype: 'hiddenfield',
                itemId: 'hiddenfielfservicename'
            },
            {
                xtype: 'checkboxfield',
                disabled: true,
                disabledCls: 'x-field',
                itemId: 'gonogochecklistbox',
                width: '80%',
                label: 'Field',
                labelWidth: '60%'
            },
            {
                xtype: 'button',
                itemId: 'editchecklist',
                width: '10%',
                text: 'Edit'
            },
            {
                xtype: 'button',
                itemId: 'viewchecklist',
                width: '10%',
                text: 'View'
            }
        ]
    },

    updateRecord: function(record) {
        // Provide an implementation to update this container's child items
        var me = this;

        me.down('#gonogochecklistbox').setLabel(record.get('label'));

        me.callParent(arguments);
    }

});