/*
 * File: app/view/NotificationsList.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.NotificationsList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.notificationslist',

    requires: [
        'Ext.XTemplate'
    ],

    config: {
        height: '80%',
        id: 'notificationslist',
        padding: 10,
        width: '25%',
        hideOnMaskTap: true,
        modal: true,
        deselectOnContainerClick: false,
        disableSelection: true,
        scrollToTopOnRefresh: false,
        store: 'notificationsstore',
        itemHeight: 20,
        pinHeaders: false,
        itemTpl: [
            '<h1>{date:date(\'d/m/Y H:i:s\')}</h1>',
            '<br />',
            '{criticity} - {label} - {description}'
        ]
    }

});