/*
 * File: app/view/CheckListList.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.CheckListList', {
    extend: 'Ext.dataview.DataView',
    alias: 'widget.checklistlist',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'MyApp.view.CheckListItem'
    ],

    config: {
        autoDestroy: false,
        modal: true,
        disableSelection: true,
        defaultType: 'checklistitem',
        store: 'checklistservices',
        useComponents: true,
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                itemId: 'navigationbar'
            },
            {
                xtype: 'button',
                bottom: '10%',
                centered: false,
                docked: 'bottom',
                height: 40,
                id: 'savechecklist',
                left: '',
                right: '40%',
                ui: 'action',
                width: '20%',
                text: 'Save'
            }
        ]
    }

});