/*
 * File: app/view/CheckListItem.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.CheckListItem', {
    extend: 'Ext.dataview.component.DataItem',
    alias: 'widget.checklistitem',

    requires: [
        'Ext.field.Checkbox',
        'MyApp.store.CheckListsState'
    ],

    config: {
        maxHeight: 70,
        padding: 10,
        layout: {
            type: 'hbox',
            align: 'center',
            pack: 'center'
        },
        items: [
            {
                xtype: 'checkboxfield',
                itemId: 'stepchecklistbox',
                width: '80%',
                label: 'Field',
                labelWidth: '60%'
            }
        ]
    },

    updateRecord: function(record) {
        // Provide an implementation to update this container's child items
        var me = this;

        if ( localStorage.getItem("gonogoMode") == "view"){
            me.down('#stepchecklistbox').disable();
        }

        var checklistsstateStore = Ext.getStore('checklistsstate');
        checklistsstateStore.clearFilter();
        checklistsstateStore.filter('gonogo', 'Challenger 2013');

        me.down('#stepchecklistbox').uncheck();
        if(checklistsstateStore.getAt(record.get('id')).get('done')){
            me.down('#stepchecklistbox').check();
        }

        me.down('#stepchecklistbox').setLabel(record.get('label'));

        me.callParent(arguments);



    }

});