/*
 * File: app/view/FOPDetailView.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.FOPDetailView', {
    extend: 'Ext.Container',

    config: {
        items: [
            {
                xtype: 'grid',
                docked: 'top',
                height: 1136,
                title: 'FOPDetailGrid',
                columns: [
                    {
                        xtype: 'column',
                        width: 110,
                        text: 'Line'
                    },
                    {
                        xtype: 'column',
                        width: 170,
                        text: 'Action'
                    },
                    {
                        xtype: 'column',
                        width: 130,
                        text: 'Entity'
                    },
                    {
                        xtype: 'column',
                        width: 130,
                        text: 'Label'
                    },
                    {
                        xtype: 'column',
                        width: 130,
                        text: 'Time'
                    },
                    {
                        xtype: 'column',
                        width: 160,
                        text: 'Report'
                    }
                ]
            }
        ]
    }

});