/*
 * File: app/view/FOPMainView.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.FOPMainView', {
    extend: 'Ext.Container',
    alias: 'widget.fopview',

    requires: [
        'Ext.grid.Grid',
        'Ext.grid.column.Date'
    ],

    config: {
        items: [
            {
                xtype: 'grid',
                docked: 'top',
                height: 1216,
                title: 'FOPMainGrid',
                columns: [
                    {
                        xtype: 'column',
                        width: 50,
                        text: 'C'
                    },
                    {
                        xtype: 'column',
                        width: 50,
                        text: 'T'
                    },
                    {
                        xtype: 'column',
                        width: 110,
                        text: 'Status'
                    },
                    {
                        xtype: 'column',
                        width: 50,
                        text: 'I'
                    },
                    {
                        xtype: 'column',
                        width: 110,
                        text: 'Code'
                    },
                    {
                        xtype: 'column',
                        width: 110,
                        text: 'Label'
                    },
                    {
                        xtype: 'column',
                        width: 110,
                        text: 'Mode'
                    },
                    {
                        xtype: 'datecolumn',
                        width: 110,
                        text: 'Start',
                        format: 'MM/DD/YYYY HH:MM:SS'
                    },
                    {
                        xtype: 'datecolumn',
                        width: 110,
                        text: 'End',
                        format: 'MM/DD/YYYY HH:MM:SS'
                    },
                    {
                        xtype: 'column',
                        width: 110,
                        text: 'Owner'
                    }
                ]
            }
        ]
    }

});