/*
 * File: app/view/GonogoCheckListView.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.GonogoCheckListView', {
    extend: 'Ext.navigation.View',
    alias: 'widget.gonogochecklistview',

    requires: [
        'MyApp.view.GonogoServicesList',
        'Ext.navigation.Bar',
        'Ext.dataview.DataView'
    ],

    config: {
        navigationBar: {
            docked: 'top',
            itemId: 'navigationbar'
        },
        items: [
            {
                xtype: 'gonogoserviceslist'
            }
        ]
    }

});