/*
 * File: app/view/GonogoItem.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.GonogoItem', {
    extend: 'Ext.dataview.component.DataItem',
    alias: 'widget.gonogoitem',

    requires: [
        'Ext.Container',
        'Ext.Label',
        'Ext.Button'
    ],

    config: {
        maxHeight: 70,
        padding: 10,
        layout: 'hbox',
        items: [
            {
                xtype: 'container',
                flex: 1,
                centered: false,
                height: 50,
                html: '<img src="resources/images/satellite_ico.png" :>',
                maxWidth: 50,
                minWidth: 50,
                width: 50,
                layout: 'fit'
            },
            {
                xtype: 'label',
                flex: 1,
                height: 50,
                itemId: 'gonogoitemname'
            },
            {
                xtype: 'button',
                flex: 1,
                height: 50,
                itemId: 'gonogobutton',
                maxWidth: 70,
                minWidth: 70,
                width: 70,
                text: 'GO'
            }
        ]
    },

    updateRecord: function(record) {
        // Provide an implementation to update this container's child items
        var me = this;

        me.down('#gonogoitemname').setHtml(record.get('label'));

        me.callParent(arguments);
    }

});