/*
 * File: app/view/GraphicTM.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.GraphicTM', {
    extend: 'Ext.Panel',
    alias: 'widget.graphictm',

    requires: [
        'Ext.TitleBar',
        'Ext.chart.CartesianChart',
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Line',
        'Ext.chart.interactions.PanZoom'
    ],

    config: {
        height: '100%',
        width: '100%',
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Graphic'
            },
            {
                xtype: 'chart',
                height: '100%',
                width: '100%',
                colors: [
                    '#115fa6',
                    '#94ae0a',
                    '#a61120',
                    '#ff8809',
                    '#ffd13e',
                    '#a61187',
                    '#24ad9a',
                    '#7c7474',
                    '#a66111'
                ],
                store: 'GraphStore',
                axes: [
                    {
                        type: 'category'
                    },
                    {
                        type: 'numeric',
                        grid: {
                            odd: {
                                fill: '#e8e8e8'
                            }
                        },
                        position: 'left'
                    }
                ],
                series: [
                    {
                        type: 'line',
                        colors: 'rgba(0,200,0,0.3)',
                        style: {
                            smooth: true,
                            stroke: 'rgb(0,200,0)',
                            
                        },
                        xField: 'x',
                        yField: 'y',
                        fill: false
                    }
                ],
                interactions: [
                    {
                        type: 'panzoom'
                    }
                ]
            }
        ]
    }

});