/*
 * File: app/view/MenuList.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MenuList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.menulist',

    requires: [
        'Ext.XTemplate'
    ],

    config: {
        border: 3,
        centered: false,
        height: '80%',
        hidden: false,
        id: 'menulist',
        itemId: 'menulist',
        style: 'border-color: black; border-style: solid; border-radius:10px;',
        width: '50%',
        autoDestroy: false,
        hideOnMaskTap: true,
        modal: true,
        disableSelection: true,
        store: 'menustore',
        grouped: true,
        infinite: true,
        striped: true,
        variableHeights: true,
        itemTpl: [
            '<div>{label}</div>'
        ]
    }

});