/*
 * File: app/view/ProjectSolvingNav.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ProjectSolvingNav', {
    extend: 'Ext.navigation.View',
    alias: 'widget.projectsolvingnav',

    requires: [
        'MyApp.view.ProjectSolvingList',
        'Ext.dataview.List',
        'Ext.navigation.Bar'
    ],

    config: {
        items: [
            {
                xtype: 'projectsolvinglist'
            }
        ],
        navigationBar: {
            docked: 'top',
            hidden: true
        }
    }

});