/*
 * File: app/view/WikiView.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.WikiView', {
    extend: 'Ext.Panel',
    alias: 'widget.wikiview',

    config: {
        fullscreen: true,
        html: '<div style="-webkit-overflow-scrolling:touch; overflow:auto;width=100%;height=100%;position:fixed;top:0;left:0;float:left;z-index:99;"><iframe style="position:fixed;top:0;left:0;float:left;z-index:1;" width="100%" height="100%" src="https://192.168.56.101/mediawiki-1.21.2/index.php/Main_Page"></iframe></div>',
        layout: 'fit',
        scrollable: true
    }

});