/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    stores: [
        'MenuStore',
        'ProblemSolvingStore',
        'TimeZoneStore',
        'NotificationStore',
        'LanguageStore'
    ],
    views: [
        'AuthView',
        'MenuList',
        'PreferencesView',
        'HomeView',
        'MainNav',
        'NotificationsList',
        'WikiView',
        'ProjectSolvingList',
        'ProjectSolvingNav'
    ],
    controllers: [
        'AuthView',
        'PreferencesView',
        'MainNav',
        'ProjectSolvingNav'
    ],
    name: 'MyApp',

    launch: function() {
        //Pour la mise à jour des notifications
        var timerCheckForNotifications;
        Ext.create('MyApp.view.AuthView', {fullscreen: true});
    }

});
