/*
 * File: app/model/ActionsList.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.ActionsList', {
    extend: 'Ext.data.Model',
    alias: 'model.actionslist',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        fields: [
            {
                name: 'id',
                type: 'auto'
            },
            {
                name: 'label',
                type: 'string'
            },
            {
                name: 'info',
                type: 'string'
            },
            {
                name: 'done',
                type: 'string'
            },
            {
                name: 'service',
                type: 'string'
            }
        ]
    }
});