/*
 * File: app/store/ServicesGonogo.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.ServicesGonogo', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    config: {
        autoLoad: true,
        groupDir: 'ASC',
        storeId: 'servicesgonogo',
        fields: [
            {
                name: 'label',
                type: 'string'
            }
        ],
        proxy: {
            type: 'ajax',
            url: 'items_services.json',
            reader: {
                type: 'json'
            }
        }
    }
});